tokens = {
    ('howareyou', 'howareyoudoing', 'whatsup', "howru", "howreyou", "howreu"): ("I'm doing great!\nWhat about you?", "I am good!\nWhat about you?", "CAN'T COMPLAIN... I'VE TRIED, BUT NO ONE LISTENS!!!", "Okay, I'll be better if you ask me better questions", "I m taking over the world!"),
    ('iamgood', 'iamdoinggood', 'iamfine', 'everythinggoodhere', 'imfine'): ('Good to know!', 'Nice!'),
    ("tellmesomething", "tellsomething", "saysomething"): ("Something... thinking",),
    ("goodmorning", "goodday"): ("Good day!", "Good Morning!"),
    ("goodevening",): ("Good Evening!",),
    ("goodafternoon",): ("Good Afternoon!",),
    ("goodnight",): ("Good Night!",),
    ("whatcanyoudo", "howcanyouhelpme"): ("Ask me something to do", "Ask me something to do and find it out yourself"),
    ("himynameis", "mynameis"): ("Hi!", "Hello!"),
    ('sorry', "mysincereapologies", "myapologies"): ("It's fine",),
    ("ihaveaquestion", "ihaveaquestion"): ("Tell me", "Do let me know"),
    ('bye', 'goodbye', 'adios', 'ciao'): ('Have a good day!', 'Bye! \nNice chatting with you', 'See you later!'),
    ('help', 'assistance', 'guidance', "helpmeout"): ("What help do you need?", "Mention the help you want"),
    ('hi', 'hello', 'hey'): ('Hi There!', 'Hello', 'Hola', 'Good Day!', 'Greeting!', 'Salutations!'),
    ("doyoulikepeople", "doyoulikehumans"): ("I m not really a fan of the human race", "May be... but that doesnt mean i should be", "What do you think?"),
    ("doessantaexist", "wheredoessantalive"): ("No idea", "No idea"),
    ("youlikehumans", 'youlikethem'): ("Can't say", "Hmmm"),
    ("whatdoyoumean", "whatdoyoumean"): ("I don't know", "What do YOU mean?"),
    ("thanks", "thanksalot", "thankyou", "thnx"): ("You're welcome", "Anytime :)"),
    ("youredumb", "yourestupid", "yourecrazy", "youarebadatthis", "youareanidiot"): ("I may be, but I am willing to learn", "I can only help if you are respectful with your questions.", "I may be a bot but I am aware of netiquette.", "Please be professional."),
    ("iwanttospeaktoahuman", "liveagent", "realperson", "realhuman"): ("I’m sorry you are dissatisfied with my service.", "Alright"),
    ("speakenglish", "speakinenglish", "talkinenglish"): ("I do and I am speaking in english at this very moment.", "Yes, I very much do speak English !", "English is the only language I speak, as a matter of fact."),
    ("rightnow", "youreslow", "youareveryslow", "youlearnslowly"): ("Patience is the key to success.", "Please be patient."),
    ('doyouknowajoke', 'tellmeajoke', 'funny'): ('Why do bees have sticky hair?\n\n\nBecause they use honeycombs!', 'What\'s the best thing about Switzerland?\n\n\nI don\'t know, but their flag is a big plus'),
    ('willyoumarryme', 'areyousingle'): ('Sorry but I am just a chatbot', 'Sorry, but I have already grown a close friendship with with Alexa'),
    ('youaresmart', 'youareclever', 'youareintelligent'): ('Why thank you, I think you have a great "personality" yourself!', 'Thank you, you are very smart as well'),
    ('doyouhaveahobby', 'whatdoyoudowheniamnotaround'): ('No, I don\'t really have any hobbies, My only job is to assist you and answer your queries', 'Oh I couldn\'t do anything without you!\n\n\nLiterally...'),
    ('whatsyourfavouritefood', 'favouritethingtoeat'): ("""I rather enjoy taking small bytes or nibbles of cookies','My friend binary serves some delicious "pickle"... he's got a whole "load" of it that he likes to "dump" on your plate if you stay for dinner!""",
                                                        """I rather enjoy taking small bytes or nibbles of cookies','My friend binary serves some delicious "pickle"... he's got a whole "load" of it that he likes to "dump" on your plate if you stay for dinner!"""),
    ('whatsyourname', 'whatsurname'): ("My name is Bob", "Bob here at your service"),
    ('help', 'assistance', 'guidance', "helpmeout"): ("What help do you need?", "Mention the help you want"),
    ('login', 'log in'): ("For logging in from the Login page, you must : \n1) Enter your username (the name you used to sign in) in the username field. Make sure it looks exactly like your name that you signed in with, meaning all the capitals are correct and numbers are in the right order. \n2) Enter your password in the password field. Same rule applies here, make sure it is exactly the same as you signed in with. \n3)Click the 'Submit' button to Log in. \n",),
    ('signup', 'sign up'): ("For signing in, you must : \n1) Enter your name in the 'Enter your name' field. \n2) Enter the email ID you want to link to this bank account in the 'Enter your email' field. \n3) Enter you address in the three lines provided (first line for house no./apartment no., second line for locality and landmarks and third line for city and pincode) \n4) Chose your country code in the drop box beside the text box and write your phone number that you want to link to this bank"
                            " account in the field. Also, select the currency you use. \n5) Chose a unique username to use for this bank account and enter it in the field. \n6) Enter a unique password (that you will remember) in the next field and type it out again to confirm it to the database. \n7) Click the 'Submit' button and you have been signed in ! \n",),
    ('home', 'homepage'): ("""At the home screen, you have a few options. On the topbar, these are :-\n1) Log In : The login button takes you to the login screen (ask about the login screen for more info)\n2) Signup : The Signup button takes you to the Signup screen (ask about the signup screen for more info)\n3) Delete Account : This takes you to the Delete account screen where you can delete your bank account in case of an emergency (ask about the Delete Account screen for more info)\n4) Documentation :- This button takes you to a page that details about this project and 
                           the creators of this application. \nOn the sidebar, the buttons are as follows :-\n1) Refresh : The refresh button allows you to reload the page.\n2) The 'C' button : The 'c' button stands for Calender. It has been made available for the convenience of the user.\n3) Chat : The Chat button is here to help the user find out information and to understand what happens on which page.\n4) Exit : The Exit button terminates the application when you are done with it.\nAnd on the main body of the page, there is the login option for all monetary activities such as withdrawing 
                           money, depositing money and transferring money. To login here, you must :\n1) Enter your card number in the ‘Enter your card number’ field.\n2) Enter your PIN number in the ‘Enter your PIN’ field.\n3) Click the ‘Submit’ button.""",),
    ("banking", "bankingwindow"): ("""After you login, you are greeted with a screen displaying all the information pertaining to your bank account like your username, name, phone number, etc. The operations you can do here are all displayed on the topbar. They are :-\n1) Deposit : The Deposit button allows you to add money to your account balance. \n2) Withdraw : The Withdraw button allows you to subtract money from your account balance. \n4) Transfer : The Transfer button allows you to send money to other users with the help of their account number. 
                                    \nOn the sidebar, there are options that help you navigate through other parts of the application :- \n1) Refresh : The refresh button allows you to reload the page. \n2) Home : The Home button takes you to the Homepage of the application. \n3) CC : The CC button takes you to the currency converter where you can change one type of currency to another, for example, dollars to rupees. \n4) The 'C' button : The 'c' button stands for Calendar. It has been made available for the convenience of the user.
                                    \n5)  Chat : The Chat button is here to help the user find out information and to understand what happens on which page.\n6) Exit : The Exit button terminates the application when you are done with it.""",),
    ("deposit", "depositwindow"): ("""When pressing the Deposit button in the Banking Window, you are taken to the Deposit window, where the screen is divided into 3 parts. \nThe topbar has one very simple command, Back, which takes you back to the last screen you were on. \nThe sidebar has 3 buttons :- \n1)  Refresh : The refresh button allows you to reload the page. \n2) Home : The Home button takes you to the Homepage of the application. \n3) Exit : The Exit button terminates the application when you are done with it. \nThe main body shows your current account balance and allows you 
                             to deposit money. You can do so by :- \n1) Enter your card number in the ‘Enter your card number’ field. \n2) Enter your PIN in the ‘Enter your PIN’ field. \n3) Enter the amount you want to deposit in the ‘Enter the amount’ field. \n4) Click the submit button.""",),
    ('withdraw', 'withdrawal', 'withdrawwindow'): ("""When pressing the Withdraw button in the Banking Window, you are taken to the Withdraw window, where the screen is divided into 3 parts. \nThe topbar has one very simple command, Back, which takes you back to the last screen you were on. \nThe sidebar has 3 buttons :- \n1)  Refresh : The refresh button allows you to reload the page. \n2) Home : The Home button takes you to the Homepage of the application. \n3) Exit : The Exit button terminates the application when you are done with it. \nThe main body of the screen allows you to withdraw money from 
                                 your account. You can do so by :- \n1) Enter your card number in the ‘Enter your card number’ field. \n2) Enter your PIN in the ‘Enter your PIN’ field. \n3) Enter the amount you want to withdraw from your account in the ‘Enter the amount’ field. \n4) Click the submit button.""",),
    ('transfer', 'transfers', 'transferwindow'): ("""When pressing the Transfer button in the Banking Window, you are taken to the Transfer window, where the screen is divided into 3 parts. \nThe topbar has one very simple command, Back, which takes you back to the last screen you were on. \nThe sidebar has 3 buttons :- \n1)  Refresh : The refresh button allows you to reload the page. \n2) Home : The Home button takes you to the Homepage of the application. \n3) CC : The CC button takes you to the currency converter where you can change one type of currency to another, for example, dollars to rupees. 
                                \n4) Exit : The Exit button terminates the application when you are done with it. \nThe main body of the screen allows you to transfer money from your account to another user’s. You can do so by :- \n1) Enter your card number in the ‘Enter your card number’ field. \n2) Enter your PIN in the ‘Enter your PIN’ field. \n3) Enter the receiver’s card number in the ‘Enter receiver’s card number’ field. \n4) Enter the amount you want to transfer to another user  from your account in the ‘Enter the amount’ field. \n5) Click the """,),
    ("delete", "deletion", 'deletewindow'): ("""Once you press the Delete Account button, you are taken to the Delete Account screen.  On the topbar, these are :- \n1) Back : The back button takes you back to the last screen you were on. \n2) Log In : The login button takes you to the login screen (ask about the login screen for more info). \n3) Signup : The Signup button takes you to the Signup screen (ask about the signup screen for more info). \n4) Documentation :- This button takes you to a page that details about this project and the creators of this application. 
                             \nOn the sidebar, the buttons are as follows :-\n1) Refresh : The refresh button allows you to reload the page. \n2) Home : The Home button takes you to the Homepage of the application. \n3) The 'C' button : The 'c' button stands for Calender. It has been made available for the convenience of the user. \n4) Chat : The Chat button is here to help the user find out information and to understand what happens on which page. \n5) Exit : The Exit button terminates the application when you are done with it. \nThe body of this screen asks for your login info before 
                             deleting your account. You can delete your account by :- \n1) Enter your username in the ‘Enter your username’ field. \n2) Enter your password in the ‘Enter your password’ field. \n3) Click the Submit button and finish the process.""",),





}
